/*
 * generated by Xtext 2.15.0
 */
package edu.imt.dsl.jpcoffe.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import edu.imt.dsl.jpcoffe.ide.contentassist.antlr.internal.InternalJPCoffeParser;
import edu.imt.dsl.jpcoffe.services.JPCoffeGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class JPCoffeParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(JPCoffeGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, JPCoffeGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getRecipeAccess().getGroup(), "rule__Recipe__Group__0");
			builder.put(grammarAccess.getPortionNBAccess().getGroup(), "rule__PortionNB__Group__0");
			builder.put(grammarAccess.getIngredientsBlockAccess().getGroup(), "rule__IngredientsBlock__Group__0");
			builder.put(grammarAccess.getIngredientAccess().getGroup(), "rule__Ingredient__Group__0");
			builder.put(grammarAccess.getQuantityAccess().getGroup(), "rule__Quantity__Group__0");
			builder.put(grammarAccess.getToolsBlockAccess().getGroup(), "rule__ToolsBlock__Group__0");
			builder.put(grammarAccess.getToolAccess().getGroup(), "rule__Tool__Group__0");
			builder.put(grammarAccess.getStepsBlockAccess().getGroup(), "rule__StepsBlock__Group__0");
			builder.put(grammarAccess.getStepAccess().getGroup(), "rule__Step__Group__0");
			builder.put(grammarAccess.getStepAccess().getGroup_2(), "rule__Step__Group_2__0");
			builder.put(grammarAccess.getMainAccess().getRecipesAssignment(), "rule__Main__RecipesAssignment");
			builder.put(grammarAccess.getPortionNBAccess().getNbAssignment_1(), "rule__PortionNB__NbAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private JPCoffeGrammarAccess grammarAccess;

	@Override
	protected InternalJPCoffeParser createParser() {
		InternalJPCoffeParser result = new InternalJPCoffeParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public JPCoffeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(JPCoffeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
