/**
 * generated by Xtext 2.15.0
 */
package edu.imt.dsl.jpcoffe.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import edu.imt.dsl.jpcoffe.JPCoffeRuntimeModule;
import edu.imt.dsl.jpcoffe.JPCoffeStandaloneSetup;
import edu.imt.dsl.jpcoffe.ide.JPCoffeIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class JPCoffeIdeSetup extends JPCoffeStandaloneSetup {
  @Override
  public Injector createInjector() {
    JPCoffeRuntimeModule _jPCoffeRuntimeModule = new JPCoffeRuntimeModule();
    JPCoffeIdeModule _jPCoffeIdeModule = new JPCoffeIdeModule();
    return Guice.createInjector(Modules2.mixin(_jPCoffeRuntimeModule, _jPCoffeIdeModule));
  }
}
