/**
 * generated by Xtext 2.15.0
 */
package edu.imt.dsl.jpcoffe.ide;

import edu.imt.dsl.jpcoffe.ide.AbstractJPCoffeIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class JPCoffeIdeModule extends AbstractJPCoffeIdeModule {
}
