/*
 * generated by Xtext 2.15.0
 */
package edu.imt.dsl.jpcoffe.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractJPCoffeScopeProvider extends DelegatingScopeProvider {
}
