/**
 * generated by Xtext 2.15.0
 */
package edu.imt.dsl.jpcoffe.validation;

import edu.imt.dsl.jpcoffe.validation.AbstractJPCoffeValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class JPCoffeValidator extends AbstractJPCoffeValidator {
}
