/*
 * generated by Xtext 2.15.0
 */
package edu.imt.dsl.jpcoffe.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractJPCoffeValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(edu.imt.dsl.jpcoffe.jPCoffe.JPCoffePackage.eINSTANCE);
		return result;
	}
}
