/**
 * generated by Xtext 2.15.0
 */
package edu.imt.dsl.jpcoffe;

import edu.imt.dsl.jpcoffe.AbstractJPCoffeRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class JPCoffeRuntimeModule extends AbstractJPCoffeRuntimeModule {
}
