/*
 * generated by Xtext 2.15.0
 */
package edu.imt.dsl.jpcoffe.ui;

import com.google.inject.Injector;
import edu.imt.dsl.jpcoffe.ui.internal.JpcoffeActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JPCoffeExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(JpcoffeActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		JpcoffeActivator activator = JpcoffeActivator.getInstance();
		return activator != null ? activator.getInjector(JpcoffeActivator.EDU_IMT_DSL_JPCOFFE_JPCOFFE) : null;
	}

}
