/**
 * generated by Xtext 2.15.0
 */
package edu.imt.dsl.jpcoffe.jPCoffe.impl;

import edu.imt.dsl.jpcoffe.jPCoffe.Ingredient;
import edu.imt.dsl.jpcoffe.jPCoffe.IngredientsBlock;
import edu.imt.dsl.jpcoffe.jPCoffe.JPCoffePackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ingredients Block</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.imt.dsl.jpcoffe.jPCoffe.impl.IngredientsBlockImpl#getIngredientsList <em>Ingredients List</em>}</li>
 * </ul>
 *
 * @generated
 */
public class IngredientsBlockImpl extends MinimalEObjectImpl.Container implements IngredientsBlock
{
  /**
   * The cached value of the '{@link #getIngredientsList() <em>Ingredients List</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIngredientsList()
   * @generated
   * @ordered
   */
  protected EList<Ingredient> ingredientsList;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IngredientsBlockImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JPCoffePackage.Literals.INGREDIENTS_BLOCK;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Ingredient> getIngredientsList()
  {
    if (ingredientsList == null)
    {
      ingredientsList = new EObjectContainmentEList<Ingredient>(Ingredient.class, this, JPCoffePackage.INGREDIENTS_BLOCK__INGREDIENTS_LIST);
    }
    return ingredientsList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case JPCoffePackage.INGREDIENTS_BLOCK__INGREDIENTS_LIST:
        return ((InternalEList<?>)getIngredientsList()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JPCoffePackage.INGREDIENTS_BLOCK__INGREDIENTS_LIST:
        return getIngredientsList();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JPCoffePackage.INGREDIENTS_BLOCK__INGREDIENTS_LIST:
        getIngredientsList().clear();
        getIngredientsList().addAll((Collection<? extends Ingredient>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JPCoffePackage.INGREDIENTS_BLOCK__INGREDIENTS_LIST:
        getIngredientsList().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JPCoffePackage.INGREDIENTS_BLOCK__INGREDIENTS_LIST:
        return ingredientsList != null && !ingredientsList.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //IngredientsBlockImpl
