/**
 * generated by Xtext 2.15.0
 */
package edu.imt.dsl.jpcoffe.ui;

import edu.imt.dsl.jpcoffe.ui.AbstractJPCoffeUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class JPCoffeUiModule extends AbstractJPCoffeUiModule {
  public JPCoffeUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
