/**
 * generated by Xtext 2.15.0
 */
package edu.imt.dsl.jpcoffe.jPCoffe;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ingredients Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.imt.dsl.jpcoffe.jPCoffe.IngredientsBlock#getIngredientsList <em>Ingredients List</em>}</li>
 * </ul>
 *
 * @see edu.imt.dsl.jpcoffe.jPCoffe.JPCoffePackage#getIngredientsBlock()
 * @model
 * @generated
 */
public interface IngredientsBlock extends EObject
{
  /**
   * Returns the value of the '<em><b>Ingredients List</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ingredients List</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ingredients List</em>' containment reference list.
   * @see edu.imt.dsl.jpcoffe.jPCoffe.JPCoffePackage#getIngredientsBlock_IngredientsList()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getIngredientsList();

} // IngredientsBlock
