/**
 * generated by Xtext 2.15.0
 */
package edu.imt.dsl.jpcoffe.jPCoffe;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see edu.imt.dsl.jpcoffe.jPCoffe.JPCoffeFactory
 * @model kind="package"
 * @generated
 */
public interface JPCoffePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "jPCoffe";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.imt.edu/dsl/jpcoffe/JPCoffe";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "jPCoffe";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  JPCoffePackage eINSTANCE = edu.imt.dsl.jpcoffe.jPCoffe.impl.JPCoffePackageImpl.init();

  /**
   * The meta object id for the '{@link edu.imt.dsl.jpcoffe.jPCoffe.impl.MainImpl <em>Main</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.imt.dsl.jpcoffe.jPCoffe.impl.MainImpl
   * @see edu.imt.dsl.jpcoffe.jPCoffe.impl.JPCoffePackageImpl#getMain()
   * @generated
   */
  int MAIN = 0;

  /**
   * The feature id for the '<em><b>Recipes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN__RECIPES = 0;

  /**
   * The number of structural features of the '<em>Main</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.imt.dsl.jpcoffe.jPCoffe.impl.RecipeImpl <em>Recipe</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.imt.dsl.jpcoffe.jPCoffe.impl.RecipeImpl
   * @see edu.imt.dsl.jpcoffe.jPCoffe.impl.JPCoffePackageImpl#getRecipe()
   * @generated
   */
  int RECIPE = 1;

  /**
   * The number of structural features of the '<em>Recipe</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.imt.dsl.jpcoffe.jPCoffe.impl.PortionNBImpl <em>Portion NB</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.imt.dsl.jpcoffe.jPCoffe.impl.PortionNBImpl
   * @see edu.imt.dsl.jpcoffe.jPCoffe.impl.JPCoffePackageImpl#getPortionNB()
   * @generated
   */
  int PORTION_NB = 2;

  /**
   * The feature id for the '<em><b>Nb</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORTION_NB__NB = RECIPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Portion NB</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORTION_NB_FEATURE_COUNT = RECIPE_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link edu.imt.dsl.jpcoffe.jPCoffe.Main <em>Main</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Main</em>'.
   * @see edu.imt.dsl.jpcoffe.jPCoffe.Main
   * @generated
   */
  EClass getMain();

  /**
   * Returns the meta object for the containment reference list '{@link edu.imt.dsl.jpcoffe.jPCoffe.Main#getRecipes <em>Recipes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Recipes</em>'.
   * @see edu.imt.dsl.jpcoffe.jPCoffe.Main#getRecipes()
   * @see #getMain()
   * @generated
   */
  EReference getMain_Recipes();

  /**
   * Returns the meta object for class '{@link edu.imt.dsl.jpcoffe.jPCoffe.Recipe <em>Recipe</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Recipe</em>'.
   * @see edu.imt.dsl.jpcoffe.jPCoffe.Recipe
   * @generated
   */
  EClass getRecipe();

  /**
   * Returns the meta object for class '{@link edu.imt.dsl.jpcoffe.jPCoffe.PortionNB <em>Portion NB</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Portion NB</em>'.
   * @see edu.imt.dsl.jpcoffe.jPCoffe.PortionNB
   * @generated
   */
  EClass getPortionNB();

  /**
   * Returns the meta object for the attribute '{@link edu.imt.dsl.jpcoffe.jPCoffe.PortionNB#getNb <em>Nb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nb</em>'.
   * @see edu.imt.dsl.jpcoffe.jPCoffe.PortionNB#getNb()
   * @see #getPortionNB()
   * @generated
   */
  EAttribute getPortionNB_Nb();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  JPCoffeFactory getJPCoffeFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link edu.imt.dsl.jpcoffe.jPCoffe.impl.MainImpl <em>Main</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.imt.dsl.jpcoffe.jPCoffe.impl.MainImpl
     * @see edu.imt.dsl.jpcoffe.jPCoffe.impl.JPCoffePackageImpl#getMain()
     * @generated
     */
    EClass MAIN = eINSTANCE.getMain();

    /**
     * The meta object literal for the '<em><b>Recipes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAIN__RECIPES = eINSTANCE.getMain_Recipes();

    /**
     * The meta object literal for the '{@link edu.imt.dsl.jpcoffe.jPCoffe.impl.RecipeImpl <em>Recipe</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.imt.dsl.jpcoffe.jPCoffe.impl.RecipeImpl
     * @see edu.imt.dsl.jpcoffe.jPCoffe.impl.JPCoffePackageImpl#getRecipe()
     * @generated
     */
    EClass RECIPE = eINSTANCE.getRecipe();

    /**
     * The meta object literal for the '{@link edu.imt.dsl.jpcoffe.jPCoffe.impl.PortionNBImpl <em>Portion NB</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.imt.dsl.jpcoffe.jPCoffe.impl.PortionNBImpl
     * @see edu.imt.dsl.jpcoffe.jPCoffe.impl.JPCoffePackageImpl#getPortionNB()
     * @generated
     */
    EClass PORTION_NB = eINSTANCE.getPortionNB();

    /**
     * The meta object literal for the '<em><b>Nb</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PORTION_NB__NB = eINSTANCE.getPortionNB_Nb();

  }

} //JPCoffePackage
