/**
 * generated by Xtext 2.15.0
 */
package edu.imt.dsl.jpcoffe.jPCoffe;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Main</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.imt.dsl.jpcoffe.jPCoffe.JPCoffePackage#getMain()
 * @model
 * @generated
 */
public interface Main extends EObject
{
} // Main
