/**
 * generated by Xtext 2.15.0
 */
package edu.imt.dsl.jpcoffe.jPCoffe;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Portion NB</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.imt.dsl.jpcoffe.jPCoffe.PortionNB#getNb <em>Nb</em>}</li>
 * </ul>
 *
 * @see edu.imt.dsl.jpcoffe.jPCoffe.JPCoffePackage#getPortionNB()
 * @model
 * @generated
 */
public interface PortionNB extends Recipe
{
  /**
   * Returns the value of the '<em><b>Nb</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nb</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nb</em>' attribute.
   * @see #setNb(int)
   * @see edu.imt.dsl.jpcoffe.jPCoffe.JPCoffePackage#getPortionNB_Nb()
   * @model
   * @generated
   */
  int getNb();

  /**
   * Sets the value of the '{@link edu.imt.dsl.jpcoffe.jPCoffe.PortionNB#getNb <em>Nb</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nb</em>' attribute.
   * @see #getNb()
   * @generated
   */
  void setNb(int value);

} // PortionNB
