/**
 * generated by Xtext 2.15.0
 */
package edu.imt.dsl.jpcoffe.jPCoffe;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Steps Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.imt.dsl.jpcoffe.jPCoffe.StepsBlock#getStepsList <em>Steps List</em>}</li>
 * </ul>
 *
 * @see edu.imt.dsl.jpcoffe.jPCoffe.JPCoffePackage#getStepsBlock()
 * @model
 * @generated
 */
public interface StepsBlock extends EObject
{
  /**
   * Returns the value of the '<em><b>Steps List</b></em>' containment reference list.
   * The list contents are of type {@link edu.imt.dsl.jpcoffe.jPCoffe.Step}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Steps List</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Steps List</em>' containment reference list.
   * @see edu.imt.dsl.jpcoffe.jPCoffe.JPCoffePackage#getStepsBlock_StepsList()
   * @model containment="true"
   * @generated
   */
  EList<Step> getStepsList();

} // StepsBlock
