/*
 * generated by Xtext 2.15.0
 */
package edu.imt.dsl.jpcoffe


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class JPCoffeStandaloneSetup extends JPCoffeStandaloneSetupGenerated {

	def static void doSetup() {
		new JPCoffeStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
