/*
 * generated by Xtext 2.15.0
 */
package edu.imt.dsl.jpcoffe.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class JPCoffeAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("edu/imt/dsl/jpcoffe/parser/antlr/internal/InternalJPCoffe.tokens");
	}
}
