/**
 * generated by Xtext 2.15.0
 */
package edu.imt.dsl.jpcoffe.scoping;

import edu.imt.dsl.jpcoffe.scoping.AbstractJPCoffeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class JPCoffeScopeProvider extends AbstractJPCoffeScopeProvider {
}
